const { v4: uuidv4 } = require('uuid');

/**
 * Mock land dispute cases for BhoomiChain AI.
 * Modelled on realistic Indian land dispute data from Jharkhand/Ranchi region.
 * Replace this with PostgreSQL/Prisma queries when the DB is ready.
 */
const mockCases = [
  {
    id: 'CASE-2024-001',
    title: 'Agricultural Land Encroachment — Ranchi District',
    caseNumber: 'RAN/LD/2024/001',
    status: 'ACTIVE',
    priority: 'HIGH',
    category: 'Encroachment',
    district: 'Ranchi',
    state: 'Jharkhand',
    taluka: 'Ratu',
    village: 'Nagri',
    surveyNumber: '45/A',
    area: '2.5 acres',
    landType: 'Agricultural',
    plaintiff: 'Ramesh Kumar Mahto',
    defendant: 'Suresh Singh',
    filedDate: '2024-01-15',
    hearingDate: '2024-08-20',
    court: 'Ranchi District Court',
    judge: 'Hon. Justice Priya Sharma',
    description:
      'Unauthorized construction on agricultural land parcel. Plaintiff claims ancestral ownership backed by revenue records dating to 1952.',
    documents: [
      { name: 'Sale Deed 1952', type: 'PDF', verified: true, hash: 'sha256:a1b2c3d4e5' },
      { name: 'Revenue Record', type: 'PDF', verified: true, hash: 'sha256:f6g7h8i9j0' },
      { name: 'Survey Map', type: 'Image', verified: false, hash: null },
    ],
    timeline: [
      { date: '2024-01-15', event: 'Case Filed', description: 'FIR registered at Ratu Police Station' },
      { date: '2024-02-01', event: 'Documents Submitted', description: 'Revenue records and sale deed submitted' },
      { date: '2024-03-10', event: 'Site Inspection', description: 'Revenue inspector visited the site' },
      { date: '2024-05-15', event: 'First Hearing', description: 'Preliminary hearing at Ranchi District Court' },
      { date: '2024-08-20', event: 'Next Hearing', description: 'Final arguments scheduled' },
    ],
    aiSummary: null,
    coordinates: { lat: 23.3441, lng: 85.3096 },
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-08-01T14:20:00Z',
  },
  {
    id: 'CASE-2024-002',
    title: 'Tribal Land Rights Dispute — Khunti',
    caseNumber: 'KHU/LD/2024/002',
    status: 'PENDING',
    priority: 'CRITICAL',
    category: 'Tribal Rights',
    district: 'Khunti',
    state: 'Jharkhand',
    taluka: 'Khunti',
    village: 'Torpa',
    surveyNumber: '12/B',
    area: '5.2 acres',
    landType: 'Tribal Forest Land',
    plaintiff: 'Birsa Munda Gram Sabha',
    defendant: 'State Government',
    filedDate: '2024-02-10',
    hearingDate: '2024-09-05',
    court: 'Jharkhand High Court',
    judge: 'Hon. Chief Justice Arun Kumar',
    description:
      'Gram Sabha claims rights over traditionally cultivated forest land under Forest Rights Act 2006. Land proposed for infrastructure project.',
    documents: [
      { name: 'Gram Sabha Resolution', type: 'PDF', verified: true, hash: 'sha256:k1l2m3n4o5' },
      { name: 'Forest Rights Application', type: 'PDF', verified: true, hash: 'sha256:p6q7r8s9t0' },
      { name: 'Government Order', type: 'PDF', verified: false, hash: null },
    ],
    timeline: [
      { date: '2024-02-10', event: 'Case Filed', description: 'PIL filed at Jharkhand High Court' },
      { date: '2024-03-01', event: 'Notice Issued', description: 'Court issues notice to State Government' },
      { date: '2024-04-20', event: 'Govt Reply', description: 'Government submits counter-affidavit' },
      { date: '2024-09-05', event: 'Next Hearing', description: 'Final arguments' },
    ],
    aiSummary: null,
    coordinates: { lat: 23.0728, lng: 85.2776 },
    createdAt: '2024-02-10T09:00:00Z',
    updatedAt: '2024-07-15T11:00:00Z',
  },
  {
    id: 'CASE-2024-003',
    title: 'Property Boundary Dispute — Dhanbad',
    caseNumber: 'DHA/LD/2024/003',
    status: 'RESOLVED',
    priority: 'MEDIUM',
    category: 'Boundary Dispute',
    district: 'Dhanbad',
    state: 'Jharkhand',
    taluka: 'Dhanbad',
    village: 'Jharia',
    surveyNumber: '78/C',
    area: '0.8 acres',
    landType: 'Residential',
    plaintiff: 'Meena Devi',
    defendant: 'Anil Kumar Verma',
    filedDate: '2023-11-05',
    hearingDate: '2024-03-15',
    court: 'Dhanbad Sub-Divisional Court',
    judge: 'Hon. SDM Rakesh Pandey',
    description:
      'Boundary wall constructed 3 feet into plaintiff\'s land. Survey records confirmed encroachment. Settled through mediation.',
    documents: [
      { name: 'Survey Report', type: 'PDF', verified: true, hash: 'sha256:u1v2w3x4y5' },
      { name: 'Mediation Agreement', type: 'PDF', verified: true, hash: 'sha256:z6a7b8c9d0' },
    ],
    timeline: [
      { date: '2023-11-05', event: 'Case Filed', description: 'Application submitted at SDM office' },
      { date: '2023-12-01', event: 'Survey Ordered', description: 'Court orders boundary survey' },
      { date: '2024-01-10', event: 'Survey Done', description: 'Survey confirms encroachment of 3 feet' },
      { date: '2024-02-20', event: 'Mediation', description: 'Parties agree to mediation' },
      { date: '2024-03-15', event: 'RESOLVED', description: 'Case resolved with boundary wall relocation order' },
    ],
    aiSummary: 'Case resolved: boundary wall moved back 3 feet. Agreement signed and registered.',
    coordinates: { lat: 23.7957, lng: 86.4304 },
    createdAt: '2023-11-05T08:00:00Z',
    updatedAt: '2024-03-15T17:00:00Z',
  },
  {
    id: 'CASE-2024-004',
    title: 'Fraudulent Sale Deed — Hazaribagh',
    caseNumber: 'HAZ/LD/2024/004',
    status: 'ACTIVE',
    priority: 'HIGH',
    category: 'Fraud',
    district: 'Hazaribagh',
    state: 'Jharkhand',
    taluka: 'Hazaribagh',
    village: 'Katkamsandi',
    surveyNumber: '33/D',
    area: '1.2 acres',
    landType: 'Commercial',
    plaintiff: 'Kavita Singh',
    defendant: 'Pankaj Sharma & Associates',
    filedDate: '2024-03-20',
    hearingDate: '2024-10-01',
    court: 'Hazaribagh Sessions Court',
    judge: 'Hon. Sessions Judge Mohan Lal',
    description:
      'Plaintiff alleges forged sale deed used to transfer commercial plot. Document blockchain verification reveals hash mismatch on key deed.',
    documents: [
      { name: 'Original Sale Deed', type: 'PDF', verified: true, hash: 'sha256:e1f2g3h4i5' },
      { name: 'Alleged Forged Deed', type: 'PDF', verified: false, hash: 'sha256:MISMATCH' },
      { name: 'Forensic Report', type: 'PDF', verified: true, hash: 'sha256:j6k7l8m9n0' },
    ],
    timeline: [
      { date: '2024-03-20', event: 'FIR Filed', description: 'FIR under IPC 420 and 467' },
      { date: '2024-04-05', event: 'Forensic Sent', description: 'Documents sent for forensic analysis' },
      { date: '2024-05-01', event: 'Forensic Report', description: 'Report confirms forgery' },
      { date: '2024-10-01', event: 'Next Hearing', description: 'Charge framing hearing' },
    ],
    aiSummary: null,
    coordinates: { lat: 23.9975, lng: 85.3621 },
    createdAt: '2024-03-20T12:00:00Z',
    updatedAt: '2024-08-10T09:30:00Z',
  },
  {
    id: 'CASE-2024-005',
    title: 'Inheritance Land Dispute — Gumla',
    caseNumber: 'GUM/LD/2024/005',
    status: 'PENDING',
    priority: 'LOW',
    category: 'Inheritance',
    district: 'Gumla',
    state: 'Jharkhand',
    taluka: 'Gumla',
    village: 'Sisai',
    surveyNumber: '99/E',
    area: '3.8 acres',
    landType: 'Agricultural',
    plaintiff: 'Sunita Devi & 2 others',
    defendant: 'Rajendra Oraon',
    filedDate: '2024-04-01',
    hearingDate: '2024-11-10',
    court: 'Gumla District Court',
    judge: 'Hon. Justice Anjali Kumari',
    description:
      'Three sisters claim equal share in ancestral agricultural land. Sole male heir disputes claim citing customary tribal law.',
    documents: [
      { name: 'Death Certificate (Father)', type: 'PDF', verified: true, hash: 'sha256:o1p2q3r4s5' },
      { name: 'Birth Certificates', type: 'PDF', verified: true, hash: 'sha256:t6u7v8w9x0' },
    ],
    timeline: [
      { date: '2024-04-01', event: 'Case Filed', description: 'Civil suit filed at Gumla District Court' },
      { date: '2024-11-10', event: 'Next Hearing', description: 'Arguments on tribal inheritance law' },
    ],
    aiSummary: null,
    coordinates: { lat: 23.0441, lng: 84.5346 },
    createdAt: '2024-04-01T11:00:00Z',
    updatedAt: '2024-04-01T11:00:00Z',
  },
  {
    id: 'CASE-2024-006',
    title: 'Government Land Acquisition Dispute — Bokaro',
    caseNumber: 'BOK/LD/2024/006',
    status: 'ACTIVE',
    priority: 'HIGH',
    category: 'Acquisition',
    district: 'Bokaro',
    state: 'Jharkhand',
    taluka: 'Chas',
    village: 'Sector 4',
    surveyNumber: '201/F',
    area: '12.0 acres',
    landType: 'Mixed',
    plaintiff: 'Bokaro Farmers Collective',
    defendant: 'Jharkhand Industrial Development Corporation',
    filedDate: '2024-05-12',
    hearingDate: '2024-12-01',
    court: 'Jharkhand High Court',
    judge: 'Hon. Justice Sanjay Mishra',
    description:
      'Farmers challenge inadequate compensation for land acquired for industrial corridor. Seek market value assessment.',
    documents: [
      { name: 'Acquisition Notice', type: 'PDF', verified: true, hash: 'sha256:y1z2a3b4c5' },
      { name: 'Compensation Award', type: 'PDF', verified: true, hash: 'sha256:d6e7f8g9h0' },
      { name: 'Market Valuation Report', type: 'PDF', verified: false, hash: null },
    ],
    timeline: [
      { date: '2024-05-12', event: 'Case Filed', description: 'Writ petition at Jharkhand High Court' },
      { date: '2024-06-01', event: 'Stay Order', description: 'Court stays acquisition proceedings' },
      { date: '2024-12-01', event: 'Next Hearing', description: 'Valuation hearing' },
    ],
    aiSummary: null,
    coordinates: { lat: 23.6693, lng: 85.9897 },
    createdAt: '2024-05-12T14:00:00Z',
    updatedAt: '2024-06-10T10:00:00Z',
  },
];

/**
 * Statistics for the dashboard
 */
const getStatistics = () => ({
  totalCases: mockCases.length,
  activeCases: mockCases.filter(c => c.status === 'ACTIVE').length,
  pendingCases: mockCases.filter(c => c.status === 'PENDING').length,
  resolvedCases: mockCases.filter(c => c.status === 'RESOLVED').length,
  criticalCases: mockCases.filter(c => c.priority === 'CRITICAL').length,
  byCategory: {
    Encroachment: mockCases.filter(c => c.category === 'Encroachment').length,
    TribalRights: mockCases.filter(c => c.category === 'Tribal Rights').length,
    BoundaryDispute: mockCases.filter(c => c.category === 'Boundary Dispute').length,
    Fraud: mockCases.filter(c => c.category === 'Fraud').length,
    Inheritance: mockCases.filter(c => c.category === 'Inheritance').length,
    Acquisition: mockCases.filter(c => c.category === 'Acquisition').length,
  },
  byDistrict: {
    Ranchi: mockCases.filter(c => c.district === 'Ranchi').length,
    Khunti: mockCases.filter(c => c.district === 'Khunti').length,
    Dhanbad: mockCases.filter(c => c.district === 'Dhanbad').length,
    Hazaribagh: mockCases.filter(c => c.district === 'Hazaribagh').length,
    Gumla: mockCases.filter(c => c.district === 'Gumla').length,
    Bokaro: mockCases.filter(c => c.district === 'Bokaro').length,
  },
});

module.exports = { mockCases, getStatistics };
